[INTERNAL] ui5 serve: Log warning when accepting remote connections
SAP/ui5-cli pull request #399
Opened 2020-12-07 14:09 UTC by RandomByte

Since the use of the --accept-remote-connections parameter might
indicate the intent to use the server in a productive environment, we
warn users not to do that.

And even in development environments, exposing the server to the network
might be a security risk for the system. Therefore we also warn on some
of those aspects.

Resolves: https://github.com/SAP/ui5-tooling/issues/326

2020-12-07 14:11 UTC, RandomByte commented
This is what it looks like:

![Screenshot 2020-12-07 at 15 10 17](https://user-images.githubusercontent.com/1589939/101360709-53644300-389e-11eb-80dc-53940e5bfac3.png)

The last sentence is especially long. I'm open for suggestions

2020-12-08 08:21 UTC, KlattG requested changes
Just some small suggestions.

2020-12-08 08:21 UTC, KlattG commented on lib/cli/commands/serve.js
> +			"* Vulnerable (custom-) middleware can pose a threat to your system when exposed to the network"));
```suggestion
			"* Vulnerable (custom-)middleware can pose a threat to your system when exposed to the network"));
```

2020-12-08 08:21 UTC, KlattG commented on lib/cli/commands/serve.js
> +			"* This server is intended for development purposes only. Do not use in production!"));
```suggestion
			"* This server is intended for development purposes only. Do not use it in production."));
```

2020-12-08 09:22 UTC, RandomByte commented
Thanks @KlattG!

2020-12-08 09:30 UTC, KlattG approved these changes

2020-12-09 08:49 UTC, matz3 approved these changes

2020-12-09 09:02 UTC, merged