[INTERNAL] Support Node.js pre-release versions
SAP/ui5-cli pull request #458
Opened 2021-09-28 13:14 UTC by larskissel

Support to use the UI5 Tooling with a Node.js pre-release
version. In case of using a pre-release version a warning
will be reported that for productive use only stable versions
should be used.

Fixes: https://github.com/SAP/ui5-tooling/issues/550

2021-09-28 17:36 UTC, RandomByte requested changes
I'd propose a different commit message: `[FIX] Allow Node.js pre-release versions`

2021-09-28 22:51 UTC, codeworrior commented
I second Merlin. Should we also link to https://nodejs.org/en/about/releases/ for clarity about the terms "unstable", "stable" etc.?

Something along '...For the release policy of Node.js, see https://nodejs.org/en/about/releases/ ...'

2021-09-29 14:14 UTC, RandomByte approved these changes

2021-09-29 14:56 UTC, matz3 requested changes

2021-09-29 14:56 UTC, matz3 commented on test/bin/ui5.js
> +	const sandbox = sinon.createSandbox();
Is it required to create a sandbox here? I would expect that you can just use the default sandbox via `sinon.stub(..)` (didn't test)

2021-09-29 15:19 UTC, matz3 approved these changes

2021-09-30 10:11 UTC, merged