WIP
SAP/ui5-cli pull request #529
Opened 2022-08-10 14:58 UTC by RandomByte

2022-10-20 13:45 UTC, RandomByte commented
Rebased onto latest `next`

2022-10-20 13:55 UTC, RandomByte commented
LGTM

2022-10-20 14:31 UTC, flovogt requested changes

2022-10-24 06:58 UTC, flovogt commented on test/bin/ui5.js
> +	t.context.ui5 = await esmock.p("../../bin/ui5.js", {
Done

2022-10-24 06:59 UTC, flovogt commented on lib/cli/cli.js
> +
Done

2022-10-24 06:59 UTC, flovogt commented on lib/cli/cli.js
> +	// Remove --no-update-notifier from argv as it's not known to yargs, but we still want to support using it
Done

2022-10-24 07:01 UTC, flovogt commented on test/lib/cli/cli.js
> +		// "yargs/helpers": {
@matz3 has coded a workaround for this issue. can be ignored for now.

2022-10-25 04:27 UTC, flovogt approved these changes

2022-10-25 04:28 UTC, merged