[INTERNAL] Align with @ui5/logger changes to named exports
SAP/ui5-cli pull request #599
Opened 2023-01-24 13:47 UTC by RandomByte

See https://github.com/SAP/ui5-logger/pull/371

2023-01-24 14:35 UTC, flovogt requested changes

2023-01-24 14:35 UTC, flovogt commented on test/lib/cli/base.js
> +			isLogLevelEnabled: t.context.loggerIsLogLevelEnabled
```suggestion
			isLogLevelEnabled: t.context.isLogLevelEnabledStub
```

2023-01-24 14:39 UTC, RandomByte commented on test/lib/cli/base.js
> +			isLogLevelEnabled: t.context.loggerIsLogLevelEnabled
Done

2023-01-24 14:41 UTC, flovogt reviewed
LGTM. Wait for logger release for final approval.

2023-01-25 09:19 UTC, flovogt approved these changes

2023-01-25 09:35 UTC, merged