[FIX] ui5 init: Improve error message
SAP/ui5-cli pull request #661
Opened 2023-10-26 14:16 UTC by matz3

Fixes: https://github.com/SAP/ui5-tooling/issues/306

2023-10-26 18:07 UTC, KlattG requested changes

2023-10-26 18:07 UTC, KlattG commented on lib/init/init.js
>  	message += "Libraries should only have a 'src' and (optional) 'test' folder.";
```suggestion
	message += "Libraries should only have an 'src' and (optional) 'test' folder.";
```

2023-10-26 18:07 UTC, KlattG commented on lib/init/init.js
> +	message += "In case you are about to start a new project, please refer to:\n";
```suggestion
	message += "If you are about to start a new project, please refer to:\n";
```

2023-10-26 18:07 UTC, KlattG commented on test/lib/init/init.js
> +Libraries should only have a 'src' and (optional) 'test' folder.
```suggestion
Libraries should only have an 'src' and (optional) 'test' folder.
```

2023-10-26 18:07 UTC, KlattG commented on test/lib/init/init.js
> +In case you are about to start a new project, please refer to:
```suggestion
If you are about to start a new project, please refer to:
```

2023-10-27 13:42 UTC, flovogt approved these changes

2023-10-30 08:07 UTC, merged